ChrisMarekPhotographyCore/Controllers/AjaxController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Hosting;

namespace ChrisMarekPhotography.Controllers
{

    public class AjaxController : ControllerBase
    {
        public AjaxController(IHttpContextAccessor httpContextAccessor, IMemoryCache cache, IWebHostEnvironment host, IDao dao, IPathManager serverPathManager) : base(httpContextAccessor, cache, host, dao, serverPathManager)
        {
        
        }
        /// <summary>
        /// Redirect that remains on the same page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ToogleCaching()
        {
            SetCache();
            ActionResult result = Redirect(Request.Headers["Referer"].ToString());
            return result;
        }

        /// <summary>
        /// This is the Portfolio View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet]
        public ActionResult GetPortfolioImages(string folder)
        {
            return ViewComponent("Image", new { folder });
        }

        /// <summary>
        /// This is the SlideShow that is the very first page to be displayed at start up.
        /// </summary>
        /// <param name="folder"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet]
        public ActionResult GetSlideShowImages(string folder)
        {
            return ViewComponent("SlideShowImage", new { folder });
        }


        /// <summary>
        /// This is the Images that are requested from the drop-down selection on the Images view
        /// </summary>
        /// <param name="folder"></param>
        /// <returns></returns>
        // GET: Ajax
        [HttpGet]
        public ActionResult SearchImages(string folder)
        {
            return ViewComponent("Image", new { folder });
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChrisMarekPhotographyCore/ViewComponents/HeaderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Hosting;
using ChrisMarekPhotography.Models;
using ChrisMarekPhotography;


namespace ChrisMarekPhotography.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMemoryCache _cache;
        private readonly IWebHostEnvironment _host;
        private readonly IFacade _facade;
        private readonly IDao _dao;
        private readonly IPathManager _serverPathManager;

        public HeaderViewComponent(IHttpContextAccessor httpContextAccessor, IMemoryCache cache, IWebHostEnvironment host, IDao dao, IFacade facade, IPathManager serverPathManager)
        {
            _httpContextAccessor = httpContextAccessor;
            _cache = cache;
            _host = host;
            _dao = dao;
            _facade = facade;
            _serverPathManager = serverPathManager;
        }

        public async Task<IViewComponentResult> InvokeAsync( )
        {
            IPhotosResult validatedPhotosResult = await Task.Run(()=> _facade.GetValidationResults());
            var model = new HeaderViewModel()
            {
                photosResult = validatedPhotosResult
            };
            return View("Header", model);
        }
    }
}

ChrisMarekPhotographyCore/ViewComponents/SignUpViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Threading.Tasks;

namespace ChrisMarekPhotography.ViewComponents
{
    public class SignUpViewComponent : ViewComponent
    {

        public SignUpViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Models.CustomerModel model = await Task.Run(()=> new Models.CustomerModel());
            return View("SignUp", model);
        }
    }
}

ChrisMarekPhotographyCore/ViewComponents/UrlMapViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Threading.Tasks;

namespace ChrisMarekPhotography.ViewComponents
{
    public class UrlMapViewComponent : ViewComponent
    {

        public UrlMapViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Run(()=> View("UrlMap"));
        }
    }
}

ChrisMarekPhotographyCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChrisMarekPhotography</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
<environment include="Development">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
    @*the following boostrap.css was copied from my fullframework project to fix header links
       because the boostrap that came with the .NET Core project does not work (the one above)*@
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/toastr.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.structure.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.theme.css" />
     @*<link rel="stylesheet" href="~/css/site.min.css" />*@
</environment>

</head>
<body>
    <div>
        @await Component.InvokeAsync("Header")
        <br />
        <hr class="set-hr-width"/>
        <div>
            @RenderBody()
            <div class="center-align-text">&copy; Copyright Protected</div>
            <div class="signup" align="center">
                @*see the home.css for what footer id does*@
                <footer id="footer">
                    <br />
                    <hr class="set-hr-width"/>
                    <div>
                        @await Component.InvokeAsync("SignUp")
                        <p>
                            All of the images in this website are copyrighted original works by Chris Marek, and they are protected by the United States and international copyright law.
                            Use of any content from this site, for any purpose, is strictly forbidden without express, written permission from Chris Marek Photography.
                        </p>
                        <p>&copy; @DateTime.Now.Year - Chris Marek Photography</p>
                        <div>
                            <div><a href="https://www.flickr.com/photos/30888088@N02/">Visit my photos on flicker</a></div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        @await Component.InvokeAsync("UrlMap")

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
        @*<script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/lib/toastr.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/about.js" asp-append-version="true"></script>
        <script src="~/js/images.js" asp-append-version="true"></script>
        <script src="~/js/Portfolio.js" asp-append-version="true"></script>
        <script src="~/js/shared.js" asp-append-version="true"></script>
        <script src="~/js/SlideShow.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/modernizr-2.8.3.js" asp-append-version="true"></script>
    </environment>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

ChrisMarekPhotographyCore/Views/Shared/_UrlMap.cshtml
<script type="text/javascript">
    // should map directly to Controller.Action
    var urlMap = {
        Ajax: {
            GetPortfolioImages: "@Url.Action("GetPortfolioImages", "Ajax")",
            SearchImages: "@Url.Action("SearchImages", "Ajax")",
            GetSlideShowImages: "@Url.Action("GetSlideShowImages", "Ajax")"
        },
        Home: {

        }
    };
</script>